apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: nukleon-default
  labels:
    app.kubernetes.io/component: argocd-test
    app.kubernetes.io/name: sleep
  name: argocd-test
  namespace: sandbox-denis
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    app.kubernetes.io/component: argocd-test
    app.kubernetes.io/name: sleep
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: argocd-test
        app.kubernetes.io/name: sleep
    spec:
      automountServiceAccountToken: true
      containers:
        - command: ["sleep", "infinity"]
          envFrom:
            - secretRef:
                name: test-secret
          image: >-
            image-registry.openshift-image-registry.svc:5000/sandbox-denis/alpine:latest
          imagePullPolicy: IfNotPresent
          name: sleep
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - sleep
        from:
          kind: ImageStreamTag
          name: alpine:latest
          namespace: sandbox-denis
      type: ImageChange
    - type: ConfigChange
